<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019年5月11日
 * Time: 10:28
 * Author CleverStone
 * Github https://www.github.com/cleverstone
 * Blog https://cnblogs.com/hellow-world
 */

namespace app\api\controller;

use app\common\model\Lottery;
use app\common\relation\Data2;
use app\common\RestController;
use app\common\model\JcdcBase;
use app\common\Config;

/**
 * 北京单场
 *
 * Class Login
 * @package app\api\controller
 * @author CleverStone
 * @github https://www.github.com/cleverstone
 * @blog https://cnblogs.com/hellow-world
 */
class BeijingSingle extends RestController
{
    use Data2;

    /**
     * authentication彩种列表
     *
     * @param array $disableAuthAction
     * @author CleverStone
     * @github https://www.github.com/cleverstone
     * @blog https://cnblogs.com/hellow-world
     */
    protected function init(array $disableAuthAction = [])
    {
        $disableAuthAction = ['bjSingList', 'searchbjSing'];
        parent::init($disableAuthAction); // TODO: Change the autogenerated stub
    }

    /**
     * @desc 北京单场
     * @author LiBin
     * @return \think\response\Json
     * @throws \Exception
     * @date 2019-05-13
     */
    public function bjSingList()
    {
        $data = $this->get;
        $model = new JcdcBase();
        $findData = [
            'a.match_num',//比赛编号
            'a.league_name',//联赛名称
            'a.host_name',//主队名称
            'a.guest_name',//客队名称
            'a.cutoff_time',//手动截止时间
            'a.sys_cutoff_time',//系统截止时间
            'a.rqs',//让球数
            'a.host_icon',//主队图标
            'a.guest_icon',//客队图标
            'a.jc_num',//竞彩编号
            'b.sp_spf',//胜平负奖金指数
            'a.start_time', //赛事截止时间
            'b.sp_rqspf',//让球胜平负奖金指数
            'b.sp_bf',//全场比分奖金指数
            'b.sp_jqs',//总进球数奖金指数
            'b.sp_bqc'//半全场奖金指数
        ];

        if (empty($data['type'])) {//默认胜平负
            $data['type'] = 'spf';
        }

        $where[] = ['sale_status', '=', 1];//竞彩出售中
        $footData = $model->getFootballData($where, $findData);
        if (!count($footData)) {
            return $this->asNewJson($data['type'] . 'Ret', 1, 'success', '获取成功');
        }

        //单关的方式 spf 胜平负 jqs 进球数 bf 比分 jqs 进球数 bqc 半全场
        $result = [];
        switch ($data['type']) {
            case 'spf'://胜平负
                $result = $this->oddSortBd($footData, 'spf');
                break;
            case 'jqs'://进球数
                $result = $this->oddSortBd($footData, 'jqs');
                break;
            case 'bf'://比分胜平负
                $result = $this->oddSortBd($footData, 'bf');
                break;
            case 'bqc': //半全场胜平负
                $result = $this->oddSortBd($footData, 'bqc');
                break;
        }

        //获取单关ID
        $lottery = new Lottery();
        $idData = $lottery->getOneLottery(['code' => Config::BJ_CODE], 'id');
        $funcName = $data['type'] . 'Ret';
        $code = 1;
        $status = 'success';
        $msg = '获取成功';
        $id = (string)$idData['id'];
        $args = $result;

        return json(compact('funcName', 'code', 'status', 'msg', 'id', 'args'));
    }

    /**
     * @desc 赛事检索
     * @author LiBin
     * @throws \Exception
     * @return \think\response\Json
     * @date 2019-04-08
     */
    public function searchbjSing()
    {
        $get = $this->get;
        $model = new JcdcBase();
        $findData = [
            'match_num',//比赛编号
        ];
        if (!empty($get['date'])) {
            if ($get['date'] == 1) {//今天
                $date = date('Y-m-d');
                $where[] = ['start_time', 'between', [strtotime($date . ' 00:00:00'), strtotime($date . ' 23:59:59')]];
            }
            if ($get['date'] == 2) {//明天
                $date = date("Y-m-d", strtotime("+1 day"));
                $where[] = ['start_time', 'between', [strtotime($date . ' 00:00:00'), strtotime($date . ' 23:59:59')]];
            }
        }

        $where[] = ['sale_status', '=', 1];//竞彩出售中
        $footData = $model->getBase($where, $findData);
        if (!count($footData)) {
            return $this->asNewJson('searchbjSingRet', 1, 'success', '获取成功');
        }

        $list = [];
        foreach ($footData as $k => $v) {
            $list[] = $v['match_num'];
        }

        return $this->asNewJson('searchbjSingRet', 1, 'success', '获取成功', $list);
    }
}