<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/4/13
 * Time: 14:09
 * Author CleverStone
 * Github https://www.github.com/cleverstone
 * Blog https://cnblogs.com/hellow-world
 */

namespace app\api\controller;

use app\common\model\Attention;
use app\common\RestController;
use app\common\model\Order;

/**
 * App统计页面控制器
 *
 * Class Compute
 * @package app\api\controller
 * @author CleverStone
 * @github https://www.github.com/cleverstone
 * @blog https://cnblogs.com/hellow-world
 */
class Compute extends RestController
{
    /**
     * 关闭访问控制
     *
     * @param array $disableAuthAction
     * @author CleverStone
     * @github https://www.github.com/cleverstone
     * @blog https://cnblogs.com/hellow-world
     * @api *
     */
    protected function init(array $disableAuthAction = [])
    {
        $disableAuthAction = ['redList','profit','evenRed'];
        parent::init($disableAuthAction); // TODO: Change the autogenerated stub
    }

    /**
     * 获取红榜单列表
     *
     * @throws \Exception
     * @return \think\response\Json
     * @author CleverStone
     * @github https://www.github.com/cleverstone
     * @blog https://cnblogs.com/hellow-world
     * @api *
     */
    public function redList()
    {
        $model = new Order;
        $data = $model->getRedList();

        return $this->asNewJson('redListRet', 1, 'success', '请求成功', $data);
    }

    /**
     * 红榜单详情
     *
     * @param $uid // 会员ID
     * @throws \Exception
     * @return \think\response\Json
     * @author CleverStone
     * @github https://www.github.com/cleverstone
     * @blog https://cnblogs.com/hellow-world
     * @api *
     */
    public function redDetail($uid)
    {
        $model = new Order;
        $userId = self::$uid;
        $data = $model->getRedDetail($uid,$userId);

        if (is_array($data)) {
            return $this->asNewJson('redDetailRet', 1, 'success', '请求成功', $data);
        }

        return $this->asNewJson('redDetailRet', 0, 'error', $data, []);
    }

    /**
     * @desc 连红榜
     * @author LiBin
     * @return \think\response\Json
     * @throws \Exception
     * @date 2019-04-15
     */
    public function evenRed()
    {
        $model = new Order;
        $data = $model->getEvenRed();
        return $this->asNewJson('evenRedRet', 1, 'success', '请求成功', $data);
    }

    /**
     * @desc 盈利榜
     * @author LiBin
     * @throws \Exception
     * @date 2019-04-15
     */
    public function profit()
    {
        $model = new order;
        $data = $model->profitList();
        return $this->asNewJson('profitRet', 1, 'success', '请求成功', $data);
    }
    /**
     * 关注
     *
     * @param $uid // 被关注会员ID
     * @return \think\response\Json
     * @author CleverStone
     * @github https://www.github.com/cleverstone
     * @blog https://cnblogs.com/hellow-world
     * @api *
     */
    public function attention($uid)
    {
        $model = new Attention;
        if(self::$uid === $uid){
            return $this->asNewJson('attentionRet', 1, 'success', '您无法关注您自己');
        }

        $result = $model->insertTb(self::$uid, $uid);
        if ($result === true) {
            return $this->asNewJson('attentionRet', 1, 'success', '关注成功');
        }

        return $this->asNewJson('attentionRet', 0, 'error', $result);
    }

    /**
     * 取关
     *
     * @param $attentionId // 被关注的会员ID
     * @return \think\response\Json
     * @throws \Exception
     * @author CleverStone
     * @github https://www.github.com/cleverstone
     * @blog https://cnblogs.com/hellow-world
     * @api *
     */
    public function cancelAttention($attentionId)
    {
        $model = new Attention;
        $result = $model->cancelAttention(self::$uid, $attentionId);
        if ($result) {
            return $this->asNewJson('cancelAttentionRet', 1, 'success', '取消关注成功');
        }

        return $this->asNewJson('cancelAttentionRet', 0, 'error', '取消关注失败');
    }

    /**
     * 我的关注列表
     *
     * @return \think\response\Json
     * @throws \Exception
     * @author CleverStone
     * @github https://www.github.com/cleverstone
     * @blog https://cnblogs.com/hellow-world
     * @api *
     */
    public function myAttention()
    {
        $model = new Attention;
        $data = $model->getMyAttentionList(self::$uid);
        $order = new Order;
        $result = $order->getMyAttentionData($data);

        return $this->asNewJson('myAttentionRet', 1, 'success', '请求成功', $result);
    }
}