<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/5/17 0017
 * Time: 14:58
 */

namespace app\api\controller;

use app\common\RestController;
use app\common\model\CmsNews as CmsNewsModel;
use app\common\model\Attach;


/**
 * aocai pucai 新闻列表 详情
 * Class News
 * @package app\api\controller
 */
class News extends RestController
{
    /**
     * authentication过滤掉新闻 列表 详情
     *
     * @param array $disableAuthAction
     *
     */
    protected function init(array $disableAuthAction = [])
    {
        $disableAuthAction = ['AoNewsList','PuNewsList','getNewsList'];
        parent::init($disableAuthAction); // TODO: Change the autogenerated stub
    }

    /**
     * @desc 获取澳彩的新闻列表
     * @auther ken
     * @return \think\response\Json
     * @date 2019-05-17
     */
    public function AoNewsList()
    {
        $data = $this->get;
        $number = 10;
        //判断页码
        if (empty($data['page'])) {
            $limit = '0,' . $number;
        } else {
            $limit = ($data['page'] - 1) * $number . ',' . $number;
        }

        // 获取新闻列表
        $cmsNewsModel = new CmsNewsModel();
        $newsList = $cmsNewsModel->getNewResults(1,$limit); // 澳彩
        if (empty($newsList)){
            return $this->asNewJson('AoNewsList',1,'success','获取成功',['data'=>[],'pageNumber'=>1]);
        }

        // 获取总页数
        $count = $cmsNewsModel::where(['news_type' => 1])->count('id');
        $totalPage = ceil($count / $number);

        $rdata = [];  // 数据容器
        foreach ($newsList as $key => $val){
            $rdata[$key]['id'] = $val['id'];
            $rdata[$key]['title'] = $val['title'];
            $rdata[$key]['create_time'] = $val['create_time'];
        }

        return $this->asNewJson('AoNewsList',1,'success','获取成功',['data'=>$rdata,'pageNumber'=>$totalPage]);

    }

    /**
     * @desc 获取葡彩的新闻列表
     * @auther ken
     * @return \think\response\Json
     * @date 2019-05-17
     */
    public function PuNewsList()
    {
        $data = $this->get;
        $number = 10;
        //判断页码
        if (empty($data['page'])) {
            $limit = '0,' . $number;
        } else {
            $limit = ($data['page'] - 1) * $number . ',' . $number;
        }

        // 获取新闻列表
        $cmsNewsModel = new CmsNewsModel();
        $newsList = $cmsNewsModel->getNewResults(2,$limit); // 葡彩
        if (empty($newsList)){
            return $this->asNewJson('PuNewsList',1,'success','获取成功',['data'=>[],'pageNumber'=>1]);
        }

        // 获取总页数
        $count = $cmsNewsModel::where(['news_type' => 2])->count('id');
        $totalPage = ceil($count / $number);

        $rdata = [];  // 数据容器
        foreach ($newsList as $key => $val){
            $rdata[$key]['id'] = $val['id'];
            $rdata[$key]['title'] = $val['title'];
            $rdata[$key]['create_time'] = $val['create_time'];
        }

        return $this->asNewJson('PuNewsList',1,'success','获取成功',['data'=>$rdata,'pageNumber'=>$totalPage]);

    }

    /**
     * @desc 获取葡彩的新闻详情
     * @auther ken
     * @throws \Exception
     * @return \think\response\Json
     * @date 2019-05-17
     */
    public function getNewsList()
    {
        $data = $this->get;
        $id = $data['id'];

        // 获取新闻详情
        $cmsNewsModel = new CmsNewsModel();
        $newsDetail = $cmsNewsModel->getInfo($id);
        if (empty($newsDetail)){
            return $this->asNewJson('PuNewDetail',1,'success','获取成功',['data'=>[]]);
        }

        $rdata = []; // 数据容器
        foreach ($newsDetail as $key => $val){
            $rdata[$key]['title'] = $val['title'];
            $rdata[$key]['abstract'] = $val['abstract'];
            $rdata[$key]['content'] = $val['content'];
            $rdata[$key]['img'] = Attach::getPathByAttachId($val['img']);
            $rdata[$key]['create_time'] = $val['create_time'];
        }

        return $this->asNewJson('PuNewDetail',1,'success','获取成功',['data'=>$rdata]);
    }
}