<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/5/17 0017
 * Time: 14:58
 */

namespace app\api\controller;

use app\common\RestController;
use app\common\model\Stadium as StadiumModel;
use app\common\model\StadiumType as StadiumTypeModel;
use app\common\model\Attach;


/**
 * 场馆列表 详情
 * Class Stadium
 * @package app\api\controller
 */
class Stadium extends RestController
{
    /**
     * authentication过滤掉新闻 列表 详情
     *
     * @param array $disableAuthAction
     *
     */
    protected function init(array $disableAuthAction = [])
    {
        $disableAuthAction = ['StadiumList','stadiumDetail','stadiumTypeList'];
        parent::init($disableAuthAction); // TODO: Change the autogenerated stub
    }

    /**
     * @desc 获取场馆列表
     * @return \think\response\Json
     */
    public function stadiumList()
    {
        $data = $this->get;
        if(empty($data['type'])){
            return $this->asNewJson('StadiumList', 0, 'error', '参数错误');
        }
        $number = 10;
        //判断页码
        if (empty($data['page'])) {
            $limit = '0,' . $number;
        } else {
            $limit = ($data['page'] - 1) * $number . ',' . $number;
        }

        // 获取场馆列表
        $StadiumModel = new StadiumModel();
        $newsList = $StadiumModel->getNewResults($data['type'],$limit); // 澳彩
        if (empty($newsList)){
            return $this->asNewJson('StadiumList',1,'success','获取成功',['data'=>[],'pageNumber'=>1]);
        }

        // 获取总页数
        $count = $StadiumModel::where(['stadium_type' => 1])->count('id');
        $totalPage = ceil($count / $number);

        $rdata = [];  // 数据容器
        foreach ($newsList as $key => $val){
            $rdata[$key]['id'] = $val['id'];
            $rdata[$key]['name'] = $val['name'];
            $rdata[$key]['location'] = $val['location'];
            $rdata[$key]['cost'] = $val['cost'];
            $rdata[$key]['img'] = Attach::getPathByAttachId($val['img']);
        }

        return $this->asNewJson('StadiumList',1,'success','获取成功',['data'=>$rdata,'pageNumber'=>$totalPage]);

    }

    /**
     * @desc 获取场馆详情
     * @throws \Exception
     * @return \think\response\Json
     */
    public function stadiumDetail()
    {
        $data = $this->get;
        $id = $data['id'];
        if(empty($id)){
            return $this->asNewJson('StadiumDetail', 0, 'error', '参数错误');
        }
        // 获取新闻详情
        $StadiumModel = new StadiumModel();
        $newsDetail = $StadiumModel->getInfo($id);
        if (empty($newsDetail)){
            return $this->asNewJson('StadiumDetail',1,'success','获取成功',['data'=>[]]);
        }

        $rdata = []; // 数据容器
        foreach ($newsDetail as $key => $val){
            $rdata[$key]['id'] = $val['id'];
            $rdata[$key]['name'] = $val['name'];
            $rdata[$key]['location'] = $val['location'];
            $rdata[$key]['cost'] = $val['cost'];
            $rdata[$key]['linkman'] = $val['linkman'];
            $rdata[$key]['tel'] = $val['tel'];
            $rdata[$key]['abstract'] = $val['abstract'];
            $rdata[$key]['content'] = $val['content'];
            $rdata[$key]['img'] = Attach::getPathByAttachId($val['img']);
        }

        return $this->asNewJson('StadiumDetail',1,'success','获取成功',['data'=>$rdata]);
    }

    /**
     * @desc 获取场馆类型
     * @throws \Exception
     * @return \think\response\Json
     */
    public function stadiumTypeList()
    {
        $data = $this->get;
        // 获取新闻详情
        $StadiumTypeModel = new StadiumTypeModel();
        $typeList = $StadiumTypeModel->getTypeResults();
        if (empty($typeList)){
            return $this->asNewJson('StadiumTypeList',1,'success','获取成功',['data'=>[]]);
        }

        $rdata = []; // 数据容器
        foreach ($typeList as $key => $val){
            $rdata[$key]['id'] = $val['id'];
            $rdata[$key]['name'] = $val['name'];
        }

        return $this->asNewJson('StadiumTypeList',1,'success','获取成功',['data'=>$rdata]);
    }
}