<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/4/16
 * Time: 16:31
 * Author CleverStone
 * Github https://www.github.com/cleverstone
 * Blog https://cnblogs.com/hellow-world
 */

namespace app\web\controller;

use app\common\Helper;
use app\common\model\Member;
use app\common\WebController;

/**
 * web注册页面
 *
 * Class WebReg
 * @package app\web\controller
 * @author CleverStone
 * @github https://www.github.com/cleverstone
 * @blog https://cnblogs.com/hellow-world
 */
class WebReg extends WebController
{
    /**
     * 初始化
     *
     * @author CleverStone
     * @github https://www.github.com/cleverstone
     * @blog https://cnblogs.com/hellow-world
     * @api *
     */
    public function initialize()
    {
        $isMobile = request()->isMobile();
        if (!$isMobile) {
            exit("不支持PC端注册");
        }

        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 渲染注册页
     *
     * @return mixed
     * @author CleverStone
     * @github https://www.github.com/cleverstone
     * @blog https://cnblogs.com/hellow-world
     * @api *
     */
    public function index()
    {
        $this->view->engine->layout(false);

        $isWeiXin = Helper::isWeiXin();
        $ic = input('ic') ?: '';

        return $this->fetch('web_reg/reg', [
            'ic' => $ic,
            'isWx' => $isWeiXin,
        ]);
    }

    /**
     * 表单提交
     *
     * @author CleverStone
     * @github https://www.github.com/cleverstone
     * @blog https://cnblogs.com/hellow-world
     * @api *
     */
    public function summit()
    {
        $post = $this->post;
        $validation = $this->validate($post, 'reg.add');
        if ($validation !== true) {
            return $this->asJson(0, 'error', $validation);
        }

        // 注册
        $model = new Member;
        $result = $model->webReg($post);
        if ($result === true) {
            return $this->asJson(1, 'success', '注册成功');
        }

        return $this->asJson(0, 'error', $result);
    }
}